/PROC PRINTTO LOG="C:\Users\suneel reddy\Desktop\PROJECT\SDTM\SDTM Logs\DM LOG.txt";
libname raw "D:\study\3.SAS NOTES\SDTM RAW";

proc datasets library=work kill nolist;
run;
/*data dm;
set raw.dm;
run;*/
proc copy in=raw out=work;
select dm;
run;

options validvarname=upcase;
DATA DM1;
SET DM;
STUDYID=STRIP(STUDY);
DOMAIN="DM";
USUBJID=STRIP(STUDY)||"/"||STRIP(SITE)||"/"||STRIP(PUT(SUBJECT,4.));
SUBJID=PUT(SUBJECT,4.);
SITEID=STRIP(SITE);
INVNAM=STRIP(INVNAM);
BRTHDTC=STRIP(BIRTH);
RACE=STRIP(RACE);
ETHNIC=STRIP(ETHINICITY);
SEX=STRIP(SEX);
COUNTRY=STRIP(COUNTRY);
RUN;
/*RFSTDTC RFENDTC*/

PROC SORT DATA=RAW.EX OUT=EX1;
BY STUDY SUBJECT STARTDATE;
RUN;

DATA RFSTD(RENAME=(STARTDATE=RFSTDTC)) RFEND(RENAME=(STARTDATE=RFENDTC));
SET EX1;
BY STUDY SUBJECT STARTDATE;
IF SUBJECT NE . THEN DO;
IF FIRST.SUBJECT=1 THEN OUTPUT RFSTD;
IF LAST.SUBJECT=1 THEN OUTPUT RFEND;
END;
KEEP STUDY SUBJECT STARTDATE ;
RUN;
/*RFICDTC*/

DATA RFICDT(KEEP=STUDY SUBJECT RFICDTC);
SET RAW.INFORM;
IF SUBJECT NE . THEN DO;
IF TERM='date consent signed' THEN 
RFICDTC=STRIP(PUT(ONS_DATE,IS8601DA.))||STRIP(ONS_TIME);
END;
RUN;
/*RFPENDTC*/

PROC SORT DATA=RAW.SV OUT=RFPEND;
BY STUDY SUBJID ENDDATE;
RUN;

DATA RFPENDTC(KEEP=STUDY SUBJID ENDDATE RENAME=(SUBJID=SUBJECT ENDDATE=RFPENDTC));
SET RFPEND;
BY STUDY SUBJID ENDDATE;
IF LAST.SUBJID;
RUN;

DATA DD(keep=study subject collection_date dthdtc dthfl);
SET RAW.DS;
IF propCASE(TERM)="Death" THEN DTHDTC='COLLECTION_DATE';
if dthdtc ne " " then dthfl='y';
else dthfl=" ";
RUN;

proc sort data=raw.ex out=arm;
BY STUDY SUBJECT STARTDATE;
RUN;
PROC SORT DATA=ARM NODUPKEY;
BY STUDY SUBJECT;
RUN;
 PROC FORMAT;
 VALUE $ ARMCD 'DIABEX 1000 MG'='AB'
                'SAXAGLIPTIN 5 MG/METFORMIN 1000 MG'='BA'
                'DIABEX 500 MG'='CD'
				'SAXAGLIPTIN 5 MG/METFORMIN 500-MG'='DC';
				RUN;

DATA ARM1(KEEP=STUDY SUBJECT ARMCD WHERE=(SUBJECT NE .));
SET ARM;
ARMCD=PUT(TRT,$ARMCD.);
RUN;

PROC SORT DATA=DM1;
BY STUDY SUBJECT;
RUN;
PROC SORT DATA=RFSTD;
BY STUDY SUBJECT;
RUN;
PROC SORT DATA=RFEND;
BY STUDY SUBJECT;
RUN;
PROC SORT DATA=RFICDT;
BY STUDY SUBJECT;
RUN;
PROC SORT DATA=RFPENDTC;
BY STUDY SUBJECT;
RUN;
PROC SORT DATA=DD;
BY STUDY SUBJECT;
RUN;
PROC SORT DATA=ARM1;
BY STUDY SUBJECT;
RUN;
DATA DM2;
MERGE DM1(IN=A) RFSTD RFEND RFICDT RFPENDTC DD ARM1;
BY STUDY SUBJECT;
IF A;
RUN;

PROC SORT DATA=RAW.TA OUT=TA1(KEEP=ARMCD ARM) NODUPKEY;
BY ARMCD;
RUN;

PROC SORT DATA=DM2;
BY ARMCD;
RUN;

DATA DM3;
LENGTH ARMCD $20.;
MERGE DM2(IN=A) TA1;
BY ARMCD;
IF A;
RFXSTDTC=RFSTDTC;
RFXENDTC=RFENDTC;
ACTARMCD=ARMCD;
ACTARM=ARM;
DOB=INPUT(BIRTH,YYMMDD10.);
TRTSDT=INPUT(RFSTDTC,IS8601DA.);
IF DOB NE . AND TRTSDT NE . THEN DO;
AGE=INT((TRTSDT-DOB)/365.25);
AGEU="YEARS";
END;
ELSE DO;
AGE=.;
AGEU="";
END;
DMDTC=RFICDTC;
DMDT=INPUT(RFICDTC,IS8601DA.);
IF DMDT GE TRTSDT THEN DMDY=(DMDT-TRTSDT)+1;
ELSE IF DMDT LT TRTSDT THEN DMDY=(DMDT-TRTSDT);
RUN;

proc sql;
create table DM_FINAL(label="Demographics") as select 
STUDYID "Study identifier",
DOMAIN "Domain Abbreviation",
USUBJID "unique subject identifier",
SUBJID "subject identifier",
RFSTDTC "subject reference start date/time",
RFENDTC  "Subject Reference End Date/Time",
RFXSTDTC "Date/Time of First Study Treatment",
RFXENDTC "Date/Time of Last Study Treatment",
RFICDTC "Date/Time of Informed Consent",
RFPENDTC "Date/Time of End of Participation",
DTHDTC "Date/Time of Death",
DTHFL "Subject Death Flag",
SITEID "Study Site Identifier",
INVNAM "Investigator Name",BRTHDTC "Date/time of Birth",
AGE "Age",AGEU "Age Units",
SEX "sex",RACE "race",ETHNIC "ethinicity",
ARMCD "Planned Arm Code",
ARM "Description of Planned Arm",
ACTARMCD "Actual Arm Code",
ACTARM "Description of Actual arm",
COUNTRY "Country",
DMDTC "Date/Time of Collection",
DMDY "Study Day of Collection"  from DM3;
quit;

PROC CONTENTS DATA=DM_FINAL;
RUN;

PROC SORT DATA=DM3;
BY STUDYID USUBJID;
RUN;

PROC TRANSPOSE DATA=DM3 OUT=SUPP;
VAR RANDOMIZATION_CODE;
BY STUDYID USUBJID;
RUN;

PROC SQL;
CREATE TABLE SUPPDM AS SELECT STUDYID,"DM" AS RDOMAIN,
USUBJID,"" AS IDVAR,"" AS IDVARVAL,_NAME_ AS QNAM,_LABEL_ AS QLABEL,
COL1 AS QVAL,"CRF" AS QORIG,"INVESTIGATOR" AS QEVAL FROM SUPP;
QUIT;

PROC CDISC MODEL=SDTM;
SDTM SDTMVERSION="3.1";
DOMAINDATA DATA=DM_FINAL DOMAIN=DM CATEGORY=SPECIAL;
RUN;

PROC CDISC MODEL=SDTM;
SDTM SDTMVERSION="3.2";
DOMAINDATA DATA=DM_FINAL DOMAIN=DM CATEGORY=SPECIAL;
RUN;












